### ISSUE TITLE
Repair pack mk2 and mk3 name

### ISSUE THREAD

**Issue by jokru** [jimmyjon711/FactorioExtended-Plus-Core#1]
The upgraded repair packs lack their proper names and are instead called
Unknown key: "item-name.repair-pack-mk2"
and
Unknown key: "item-name.repair-pack-mk3"
respectively.

**Comment by jimmyjon711** [comment]
Are you sure you are up to date, mine show the correct names. This is what I see with core version 0.1.3. Also technology for these items show up correctly.
![untitled](https://user-images.githubusercontent.com/6913701/44621552-dcd1e180-a85c-11e8-83b2-78f72b2eb9b2.png)

**Comment by jokru** [comment]
Hmmm, I'm in 0.1.3. Disabling all other mods doesn't help. Maybe the map's "corrupted".

**Comment by jimmyjon711** [comment]
Actually I think its because for some reason the locale for Repair Packs is in the weaponry pack, and the entity is in core. Do you have weaponry installed?

**Comment by jokru** [comment]
Nope, lol, the one we decided to skip.

**Comment by jimmyjon711** [comment]
Well I guess its a good thing because you found a bug :-)

**Comment by jimmyjon711** [comment]
@jokru the update is now uploaded to the mod portal.

**Comment by jokru** [comment]
Thanks! 
Not that it was game breaking, but it was still a bug.
