### ISSUE TITLE
Another Tier of miner

### ISSUE THREAD

**Issue by jimmyjon711** [jimmyjon711/FactorioExtended-Plus-Core#10]
Suggestion came in via discord

That takes blue circuits with another increase from 5x5 range to 7x7 mining range, update the miner costs to make tier 2 take 2 or 4 tier 1 miners, and the tier 3 miners take 2 or 4 tier 2 miners with increased costs, not even maybe increased mining values for the tier 3 over tier 2, just larger area

**Comment by billbo99** [comment]
done
