### ISSUE TITLE
Upgrade Planner bug?

### ISSUE THREAD

**Issue by GFrost86** [jimmyjon711/FactorioExtended-Plus-Core#15]
Noticed today that there is an issue using the Factorio upgrade planner with the FE+ mods.
I haven't checked every item but I notice the the Vanilla Accumulator can not be selected to be upgraded to the FE+ version, not sure it this is a FE+ bug or a Factorio bug.
Similar issue with the science labs.

**Comment by jimmyjon711** [comment]
It's because the bounding box in fe+ is smaller than the normal one(so you can walk through fields of them). This is a limitation of factorio, if the bounding boxes were the same it would upgrade them.
