### ISSUE TITLE
Mod loading issue 0.18.4 - FE+ Logistics 0.4.1

### ISSUE THREAD

**Issue by Trblz42** [jimmyjon711/FactorioExtended-Plus-Core#17]
Mods to disable:Failed to load mods: __FactorioExtended-Plus-Logistics__/data.lua:1: ...Extended-Plus-Logistics__/prototypes/entity/__init__.lua:2: ...lus-Logistics__/prototypes/entity/construction-robot.lua:28: attempt to index field '?' (a nil value)
stack traceback:
	...lus-Logistics__/prototypes/entity/construction-robot.lua:28: in main chunk
	[C]: in function 'require'
	...Extended-Plus-Logistics__/prototypes/entity/__init__.lua:2: in main chunk
	[C]: in function 'require'
	__FactorioExtended-Plus-Logistics__/data.lua:1: in main chunk
stack traceback:
	[C]: in function 'require'
	...Extended-Plus-Logistics__/prototypes/entity/__init__.lua:2: in main chunk
	[C]: in function 'require'
	__FactorioExtended-Plus-Logistics__/data.lua:1: in main chunk
stack traceback:
	[C]: in function 'require'
	__FactorioExtended-Plus-Logistics__/data.lua:1: in main chunk

Mods to be disabled:
• FactorioExtended-Plus-Logistics

**Comment by billbo99** [comment]
Its a bug in 0.18.4 .. https://forums.factorio.com/viewtopic.php?f=30&t=80965
But I had added a work around in .. https://github.com/jimmyjon711/FactorioExtended-Plus-Logistics/pull/17

**Comment by billbo99** [comment]
0.18.5 has been released,  the issue with the amination set has been fixed within base game now.
