### ISSUE TITLE
Chem Plant Not Cracking Lube Enough

### ISSUE THREAD

**Issue by Trepidati0n** [jimmyjon711/FactorioExtended-Plus-Core#19]
Seems to be a soft limit of ~600 units/sec no matter how I hook it up (even in creative).

**Comment by billbo99** [comment]
Factorio base engine has a crafting limit of one craft per tick.

There are 60x ticks per second,  and lube crafts at 10 per craft.  So 60 crafts per second at 10 per craft gets to your observed 600 fluid per second.

What you need is a BULK recipe that takes more ingredients and longer time to craft.

**Comment by billbo99** [comment]
I get around this problem with my mod "https://mods.factorio.com/mod/deadlock_stacked_recipes" combined with the mod "https://mods.factorio.com/mod/CompressedFluids".   I create recipes that uses Pressurized fluids to produce Pressurized fluids.  EG  10 High Pressure heavy oil to produce 10 High pressure lube over a 10 second crafting window.    This allows you to put more beacons and modules on your build before hitting the internal game limit.
