### ISSUE TITLE
Titanium & Productivity Modules

### ISSUE THREAD

**Issue by Jona898** [jimmyjon711/FactorioExtended-Plus-Core#20]
Hello,

I noticed, that Productivity Module in a Furnace to smelt Titanium Ore to Titanium Plate has no effect, if there is a Productivity Module in the Furnace. Also, you can’t put them in, if the recipe is in Progress. Is this intended or a bug? Because it seems off, that it isn't affected by Productivity.

Another bug is, that the Recipe from Iron Ore to Titanium Ore only allows up to Productivity Module 3 and not further for example mk4-6 from [FactorioExtended Plus Module ](https://mods.factorio.com/mod/FactorioExtended-Plus-Module). Do you know, if it is possible to allow all Productivity Modules to affect this recipe?

Kind Regards Jonathan

**Comment by billbo99** [comment]
@Jona898  .. you will need to ask "MaxelDel" the owner of "FactorioExtended Plus Module" to fix the recipes which his mk4-6 productivity modules will work for.

In his code he is using "limitation = productivity_module_limitation()"  which enables JUST the default recipes in vanila factorio against his modules.

My thought to fixing this would be to copy the current limitation assigned to the mk3 module to the mk4-6.

eg
limitation = data.raw.module["productivity-module-3"].limitation

**Comment by Jona898** [comment]
Thanks to add the Productivity Module to the titanium alloy. Should I close this Issue or can you do it as well, if you are finished?

I didn't knew it's on his side those Recepies don't allow them. Thanks for the hint.

**Comment by jimmyjon711** [comment]
Fixed by b66097be149b2bd50040bc2453c6eb7b313bc507
