### ISSUE TITLE
Create Upgraded labs

### ISSUE THREAD

**Issue by jimmyjon711** [jimmyjon711/FactorioExtended-Plus-Core#9]
Suggestion came in via discord

Tier 2 maybe tier 3 with increased costs and like maybe tier 2 lab 50% bonus takes 4 tier 1 labs + red circuits with 3 module slots and maybe a tier 3 lab with 100% bonus that takes 4 tier 2 labs with 4 module slots and blue circuits

**Comment by billbo99** [comment]
done
